### ISSUE TITLE
ImportError: cannot import name 'is_union' from 'pydantic.typing'

### ISSUE THREAD

**Issue by dshwei** [openai/openai-python#1272]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

>>> import openai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/types/__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/types/edit.py", line 6, in <module>
    from .._models import BaseModel
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_models.py", line 33, in <module>
    from ._utils import (
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_utils/__init__.py", line 2, in <module>
    from ._utils import flatten as flatten
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_utils/_utils.py", line 22, in <module>
    from .._compat import is_union as _is_union
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_compat.py", line 55, in <module>
    from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/pydantic/typing.cpython-39-x86_64-linux-gnu.so)

### To Reproduce
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7.4
            pydantic compiled: True
                 install path: /demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
                     platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
import openai 

### OS

linux

### Python version

python 3.9

### Library version

openai 1.1.0

**Comment by RobertCraigie** [comment]
Hey @dshwei, we only support Pydantic >= v1.9.0 and it looks like you're using v1.7.4, please upgrade to a later version!
