### ISSUE TITLE
DEFER_PYDANTIC_BUILD causes issues

### ISSUE THREAD

**Issue by radoshi** [openai/openai-python#1306]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Release 1.16.1 broke clients by deferring the build if pydantic models. As a result, doing a `model_dump()` on an object returned by the library can fail.

https://github.com/openai/openai-python/pull/1292/commits/bc6866eb2335d01532190d0906cad7bf9af28621

While this speeds up build times, it should be considered a breaking change and ideally, avoided. 

If the speedup is significant, we would request not using a generic envvar like `DEFER_PYDANTIC_BUILD` to revert the change, instead using something like `OPENAI_PYDANTIC_DEFER_BUILD`.

We noticed this issue with a streaming tool call message, and are not sure if other deep classes exhibit this behaviour.

### To Reproduce

1. Create a streaming tool call chat completion message.
2. Call `model_dump()` on the object.
3. Observe stack trace in pydantic serializer code.

### OS

macOS, Linux

### Python version

Python v3.11.8

### Library version

openai v1.16.1

**Comment by RobertCraigie** [comment]
Can you share a full example script to reproduce this? I can't reproduce this.

**Comment by RobertCraigie** [comment]
Thanks, even just a full stack trace would be helpful :)

**Comment by radoshi** [comment]
That's easier. I manually elided some file paths to non-library code.

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/backend--rBupBVn-py3.11/lib/python3.11/site-packages/django/core/servers/basehttp.py", line 173, in finish_response
    super().finish_response()
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 183, in finish_response
    for data in self.result:
  File "/.../backend/chat/views.py", line 91, in message_save_wrapper
    for message_chunk in generator:
  File "/.../backend/llm/handlers/openaifunction.py", line 285, in chat_streaming
    for chunk in response:
  File "/.../backend/llm/handlers/openai.py", line 73, in _traced_completion_create_streaming
    call_params["messages"] = [m.model_dump() for m in params["messages"]]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../backend/llm/handlers/openai.py", line 73, in <listcomp>
    call_params["messages"] = [m.model_dump() for m in params["messages"]]
                               ^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/backend--rBupBVn-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 314, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

`params["messages"]` is `list[ChoiceDeltaToolCall]` or `list[ChatCompletionMessageToolCall]` which blows up when `model_dump()` is called on it.

We got around this by rewriting our code to not do direct model_dump on the returned object, but that was pretty unintuitive behavior.

Let me know if you'd like me to try and isolate a repro for you.

**Comment by RobertCraigie** [comment]
What version of `pydantic` are you using? Looks like this is a pydantic bug that's been reported a couple of times: https://github.com/pydantic/pydantic/issues/7713

In the meantime you could probably fix this by setting `PYDANTIC_DEFER_BUILD` to `0` or by calling `ChatCompletionChunk.model_rebuild()`.

**Comment by radoshi** [comment]
Ooh quite possible. We're on pydantic `2.6.4`

We did fix this by `PYDANTIC_DEFER_BUILD` - this is what led to having confidence about where the bug was. Our claim is that this is an unanticipated breaking change (it broke production for a brief moment) in a minor semver update. We then backed it out and fixed it the "right way".

Ultimately, the bug doesn't block us, but it's possible that others will run into the same issue and start to see strange stacks in production.

FWIW, the name `PYDANTIC_DEFER_BUILD` is unfortunate. It's very specific to openai lib rather than all pydantic defer_build=True situations.

**Comment by RobertCraigie** [comment]
Sure, it was never intended to be public, it was just planned for internal use. But renaming it makes sense.

**Comment by radoshi** [comment]
Thanks for listening. Selfishly, we are fine with whatever y’all choose to
do here including closing as “working as intended”, since we got around
this already.

**Comment by iwaszko** [comment]
Hey, for future reference, there's a typo in the issue title and comments. The correct workaround is to set the `DEFER_PYDANTIC_BUILD` environment variable to `0`, not `PYDANTIC_DEFER_BUILD`.

**Comment by radoshi** [comment]
> Hey, for future reference, there's a typo in the issue title and comments. The correct workaround is to set the `DEFER_PYDANTIC_BUILD` environment variable to `0`, not `PYDANTIC_DEFER_BUILD`.

Oops. Thanks @iwaszko . I edited the title and the original description.

@RobertCraigie LMK if you want to just close this bug if this isn't something y'all want to address. We've resolved the issue on our end.

**Comment by lm970585581** [comment]
I also encounter the same problem when using langchain's tool call

**Comment by rdv0011** [comment]
> That's easier. I manually elided some file paths to non-library code.
> 
> ```
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 138, in run
>     self.finish_response()
>   File "/Users/.../Library/Caches/pypoetry/virtualenvs/backend--rBupBVn-py3.11/lib/python3.11/site-packages/django/core/servers/basehttp.py", line 173, in finish_response
>     super().finish_response()
>   File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 183, in finish_response
>     for data in self.result:
>   File "/.../backend/chat/views.py", line 91, in message_save_wrapper
>     for message_chunk in generator:
>   File "/.../backend/llm/handlers/openaifunction.py", line 285, in chat_streaming
>     for chunk in response:
>   File "/.../backend/llm/handlers/openai.py", line 73, in _traced_completion_create_streaming
>     call_params["messages"] = [m.model_dump() for m in params["messages"]]
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/.../backend/llm/handlers/openai.py", line 73, in <listcomp>
>     call_params["messages"] = [m.model_dump() for m in params["messages"]]
>                                ^^^^^^^^^^^^^^
>   File "/Users/.../Library/Caches/pypoetry/virtualenvs/backend--rBupBVn-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 314, in model_dump
>     return self.__pydantic_serializer__.to_python(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
> ```
> 
> `params["messages"]` is `list[ChoiceDeltaToolCall]` or `list[ChatCompletionMessageToolCall]` which blows up when `model_dump()` is called on it.
> 
> We got around this by rewriting our code to not do direct model_dump on the returned object, but that was pretty unintuitive behavior.
> 
> Let me know if you'd like me to try and isolate a repro for you.

Hi. I have faced with a similar issue when using a local LLM running on mlx server. My setup consists of aider -> litellm -> two mlx.sever. My question is how did you trace which options blows up when model_dump() is called?
[original issue](https://github.com/BerriAI/litellm/issues/9345)

**Comment by Viicos** [comment]
Hello @RobertCraigie, similar to https://github.com/pydantic/pydantic/issues/11250, I'd like to follow up on this issue. This one is quite tricky to get right, as deferring model builds can significantly improve import time, but can also cause unwanted issues on the other hand.

The first reason is that you can't be assured that models will be able to resolve forward references until they are actually used. Consider the following example:

```python
from __future__ import annotations

from pydantic import BaseModel

class Model(BaseModel):
    f: Unknown
```

If, as a library, you don't call `model_rebuild()` somewhere (e.g. as I suggested [here](https://github.com/pydantic/pydantic/issues/11250#issuecomment-2583305878), in the `__init__.py` of your module), users of your library may encounter exceptions related to unresolvable type hints when using (i.e. trying to instantiate) your library models. In most cases this is fine if the forward references in the models are guaranteed to be resolved (that is, if the forward references refer to objects defined in the same module, and explicitly providing a types namespace in `model_rebuild()` isn't required), but this is hard to tell if this is the case for the OpenAI SDK as models are automatically generated with the Stainless API.

---

The second reason (the actual issue reported here) is that OpenAPI is using `model_construct()` to populate the SDK models:

https://github.com/openai/openai-python/blob/eed877fddc0e26ab99d10157de25e3abcb95598b/src/openai/_models.py#L521-L533

And with the following example:

```python
from typing import Any

from openai import OpenAI
from pydantic import TypeAdapter

client = OpenAI(api_key='...')

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Say hi"}],
)

ta = TypeAdapter(Any)

ta.dump_json(response)
# pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

The reason is that:
- `response` is a `openai.types.chat.chat_completion.ChatCompletion` instance, which is an _incomplete_ Pydantic model, and as such doesn't have any `__pydantic_validator/serializer__` attached.
- Usually, when you instantiate an incomplete Pydantic model, it is first rebuilt (so that the `__pydantic_validator__` can actually be used). However, because `model_construct()` was used, validation was skipped and so no rebuild happened.
- `ta` is a `TypeAdapter` using the `Any` type. It means anything can be serialized using this type. To do so, Pydantic tries to infer the type of the dumped object (e.g. if it is an `int`, it will be dumped as an `int`, etc). The type of `response` is a Pydantic model, and so Pydantic tries to use the `__pydantic_serializer__` instance on the `response`'s class to dump it. However, because the model isn't built, this fails.

I'm not sure how this could be handled yet. We could either:
- Rebuild the model before using `model_construct()`.
- Rebuild the model before trying to use the `__pydantic_serializer__`.

I'll come back shortly to give updates on this.

**Comment by eugenenelou** [comment]
@Viicos thanks for the mention.

Is there a way to know if a model is already built? this could work as a workaround (at least for my case) until a proper fix is found. Because I would prefer avoiding rebuilding the model everytime.

edit: it seems model_rebuild is lazy so it should be ok.

**Comment by Viicos** [comment]
Yes `model_rebuild()` is not going to cause unnecessary builds (unless `force=True` is passed), but you can check if a model is complete with the `__pydantic_complete__` attribute.

**Comment by jezell** [comment]
hit the same thing today trying out responses api + MCP servers and trying to dump stream events

```python

                           async for e in response:
                                with tracer.start_as_current_span("llm.stream.event") as span:

                                    event : ResponseStreamEvent = e
                                    span.set_attributes({
                                        "type" : event.type,
                                        "event" : event.model_dump_json()
                                    })
```

DEFER_PYDANTIC_BUILD=0 seems to allow the code to proceed

**Comment by Ai80-8** [comment]
Stop

**Comment by marcuswood-oai** [comment]
Thanks for reporting this and for everyone’s help investigating it. I’m sorry the upgrade broke serialization in your application. The underlying issue with serializing models whose serializer build has been deferred is being tracked in [pydantic/pydantic#7713](https://github.com/pydantic/pydantic/issues/7713), where the Pydantic maintainers have [linked this report to that investigation](https://github.com/pydantic/pydantic/issues/7713#issuecomment-2977458323).

We’re closing this issue to keep tracking of the serialization bug together upstream. Please subscribe to pydantic/pydantic#7713 for progress toward a fix. The separate request to give the SDK’s environment variable a library-specific name remains tracked in [#3720](https://github.com/openai/openai-python/pull/3720), which we’re keeping open. Thank you for your patience and the useful examples shared here.
