### ISSUE TITLE
JSONDecodeError  caused by "Unterminated string" when streaming response from chat.completions.with_raw_response.create

### ISSUE THREAD

**Issue by abhahn** [openai/openai-python#1515]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am writing this bug report on behalf of a customer using an application which my team has developed using the `openai` package.  Unfortunately, I am unable to get specific repro data for this issue due to the customer's data being confidential, but it is suspected that the issue may be related to a previously closed issue #650 based on the conditions in which the problem is arising.  

In our specific case, our application is attempting to read the streaming response from the output of the `parse` method, and observing this unterminated string issue, e.g:

```
raw_response = await client.chat.completions.with_raw_response.create(**model_args)
response = raw_response.parse()
async for chunk in response:  # <-- Here is where unterminated string error occurs
   ...
```

I realize that without a specific repro with data this bug may not be actionable, but I wanted to at least ask if anyone here has any suggestions about how we might further diagnose the problem.  We got confirmation from our customer that they are using a 1.x version of the openai package, so I wanted to raise the possibility that there might be another issue somewhere else, possibly due to the transformation of the raw response to chat completion.

### To Reproduce

Repro data is unfortunately not available.

### OS

Linux

### Python version

Python 3.11

### Library version

openai v1.6.1

**Comment by RobertCraigie** [comment]
Do you have a stack trace?

**Comment by abhahn** [comment]
Here is the stack trace that was received by the person running the application.  We suspected maybe a unicode character issue, but were unable to obtain data for an exact repro:

```
2024-04-15T07:01:48.588845817Z Traceback (most recent call last):
2024-04-15T07:01:48.588850417Z   File "/tmp/8dc579713d16dd8/backend/utils.py", line 25, in format_as_ndjson
2024-04-15T07:01:48.588854317Z     async for event in r:
2024-04-15T07:01:48.588857617Z   File "/tmp/8dc579713d16dd8/app.py", line 854, in generate
2024-04-15T07:01:48.588889417Z     async for completionChunk in response:
2024-04-15T07:01:48.588894717Z   File "/tmp/8dc579713d16dd8/antenv/lib/python3.11/site-packages/openai/_streaming.py", line 116, in __aiter__
2024-04-15T07:01:48.588898317Z     async for item in self._iterator:
2024-04-15T07:01:48.588901617Z   File "/tmp/8dc579713d16dd8/antenv/lib/python3.11/site-packages/openai/_streaming.py", line 134, in __stream__
2024-04-15T07:01:48.588905017Z     data = sse.json()
2024-04-15T07:01:48.588908217Z            ^^^^^^^^^^
2024-04-15T07:01:48.588911318Z   File "/tmp/8dc579713d16dd8/antenv/lib/python3.11/site-packages/openai/_streaming.py", line 202, in json
2024-04-15T07:01:48.588925818Z     return json.loads(self.data)
2024-04-15T07:01:48.588929018Z            ^^^^^^^^^^^^^^^^^^^^^
2024-04-15T07:01:48.588932018Z   File "/opt/python/3.11.7/lib/python3.11/json/__init__.py", line 346, in loads
2024-04-15T07:01:48.588935118Z     return _default_decoder.decode(s)
2024-04-15T07:01:48.588938118Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-15T07:01:48.588941118Z   File "/opt/python/3.11.7/lib/python3.11/json/decoder.py", line 337, in decode
2024-04-15T07:01:48.588944418Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-04-15T07:01:48.588947718Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-15T07:01:48.588957318Z   File "/opt/python/3.11.7/lib/python3.11/json/decoder.py", line 353, in raw_decode
2024-04-15T07:01:48.588960618Z     obj, end = self.scan_once(s, idx)
2024-04-15T07:01:48.588963618Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-04-15T07:01:48.588966718Z json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 212 (char 211)
```

**Comment by RobertCraigie** [comment]
They are probably on an old version. There was a bug with our SSE decoder handling certain unicode characters. Please tell them to update to the latest and let us know if it still happens.
