### ISSUE TITLE
`ModuleNotFoundError: No module named 'typing_extensions'` when installed with poetry

### ISSUE THREAD

**Issue by m-danya** [openai/openai-python#1558]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Poetry incorrectly handles the dependencies of the package. As far as I understand, issues like this most often arise due to non-PEP-compliant dependency specifications. I may be wrong about this and it could be an issue with poetry itself. Thanks.

### To Reproduce

Create empty venv with Python 3.9, create basic pyproject.toml, add `openai` as a dependency using **poetry**, try to import `OpenAI` from `openai`:

```
➜  openai-breaking ls   
➜  openai-breaking python3.9 -m venv venv
➜  openai-breaking source venv/bin/activate
(venv) ➜  openai-breaking poetry init

This command will guide you through creating your pyproject.toml config.

Package name [openai-breaking]:  
Version [0.1.0]:  
Description []:  
Author [Danila Mikhaltsov <dmikhaltsov@ispras.ru>, n to skip]:  
License []:  
Compatible Python versions [^3.9]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] no
Would you like to define your development dependencies interactively? (yes/no) [yes] no
Generated file

[tool.poetry]
name = "openai-breaking"
version = "0.1.0"
description = ""
authors = ["Danila Mikhaltsov <dmikhaltsov@ispras.ru>"]
readme = "README.md"
packages = [{include = "openai_breaking"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


Do you confirm generation? (yes/no) [yes] 
(venv) ➜  openai-breaking poetry add openai 
Using version ^1.35.14 for openai

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing openai (1.35.14)
(venv) ➜  openai-breaking python 
Python 3.9.17 (main, Jun  6 2023, 20:11:21) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openai import OpenAI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmikhaltsov_/code/tmp/openai-breaking/venv/lib/python3.9/site-packages/openai/__init__.py", line 6, in <module>
    from typing_extensions import override
ModuleNotFoundError: No module named 'typing_extensions'
>>> 
```

However, when installing with pip, all is fine:

```
➜  openai-breaking python3.9 -m venv venv
➜  openai-breaking source venv/bin/activate
(venv) ➜  openai-breaking pip install openai
Collecting openai
  Downloading openai-1.35.14-py3-none-any.whl (328 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.5/328.5 kB 4.2 MB/s eta 0:00:00
Collecting sniffio
  Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting anyio<5,>=3.5.0
  Using cached anyio-4.4.0-py3-none-any.whl (86 kB)
Collecting httpx<1,>=0.23.0
  Using cached httpx-0.27.0-py3-none-any.whl (75 kB)
Collecting distro<2,>=1.7.0
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Collecting typing-extensions<5,>=4.7
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting tqdm>4
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting pydantic<3,>=1.9.0
  Downloading pydantic-2.8.2-py3-none-any.whl (423 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.9/423.9 kB 15.7 MB/s eta 0:00:00
Collecting idna>=2.8
  Using cached idna-3.7-py3-none-any.whl (66 kB)
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting httpcore==1.*
  Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)
Collecting certifi
  Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.0/163.0 kB 31.4 MB/s eta 0:00:00
Collecting h11<0.15,>=0.13
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting annotated-types>=0.4.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.20.1
  Downloading pydantic_core-2.20.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 51.6 MB/s eta 0:00:00
Installing collected packages: typing-extensions, tqdm, sniffio, idna, h11, exceptiongroup, distro, certifi, annotated-types, pydantic-core, httpcore, anyio, pydantic, httpx, openai
Successfully installed annotated-types-0.7.0 anyio-4.4.0 certifi-2024.7.4 distro-1.9.0 exceptiongroup-1.2.2 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 idna-3.7 openai-1.35.14 pydantic-2.8.2 pydantic-core-2.20.1 sniffio-1.3.1 tqdm-4.66.4 typing-extensions-4.12.2

[notice] A new release of pip is available: 23.0.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
(venv) ➜  openai-breaking python
Python 3.9.17 (main, Jun  6 2023, 20:11:21) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openai import OpenAI
>>> 
```

### OS

Linux

### Python version

3.9.17

### Library version

1.35.14

**Comment by RobertCraigie** [comment]
Hi @m-danya, as the package is installing correctly with `pip` this will be a poetry issue, please open an issue with them.

I also can't reproduce this on poetry `v1.6.1`, my output:
```
$ poetry add openai
Using version ^1.35.14 for openai

Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 15 installs, 0 updates, 0 removals

  • Installing certifi (2024.7.4)
  • Installing exceptiongroup (1.2.2)
  • Installing h11 (0.14.0)
  • Installing idna (3.7)
  • Installing sniffio (1.3.1)
  • Installing typing-extensions (4.12.2)
  • Installing annotated-types (0.7.0)
  • Installing anyio (4.4.0)
  • Installing httpcore (1.0.5)
  • Installing pydantic-core (2.20.1)
  • Installing distro (1.9.0)
  • Installing httpx (0.27.0)
  • Installing pydantic (2.8.2)
  • Installing tqdm (4.66.4)
  • Installing openai (1.35.14)

Writing lock file
```

**Comment by m-danya** [comment]
Thank you, the problem was indeed on the poetry side. I have updated the poetry (from 1.3.2 to the newest one) and it fixed my issue.
