### ISSUE TITLE
Even for Pydantic V1, getting the error "warnings is only supported in Pydantic v2" | Error while use streaming in Assistant

### ISSUE THREAD

**Issue by Vijaykrishna23** [openai/openai-python#1736]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

There seems to be a issue in this PR. I'm using pydantic V1 in my code and I'm getting the error "warnings is only supported in Pydantic v2", which is defined in`_models.py`.

Note: We are not planning to change the pydantic version to V2 as it will be a breaking change.

PR where the bug started: https://github.com/openai/openai-python/pull/1722/files

Traceback:
OpenAi error:: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 942, in accumulate_event
    block = current_message_snapshot.content[content_delta.index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app/openai/assistants/gpt/assistant_workflow.py", line 142, in handle_incoming_message
    response = await gpt_assistant_wrapper.call_assistant_and_stream(
  File "/app/app/openai/v2/api/assistants/assistant_wrapper.py", line 212, in call_assistant_and_stream
    await stream.until_done()
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 534, in until_done
    await consume_async_iterator(self)
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_streams.py", line 11, in consume_async_iterator
    async for _ in iterator:
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 501, in __aiter__
    async for item in self._iterator:
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 838, in __stream__
    await self._emit_sse_event(event)
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 690, in _emit_sse_event
    self.__current_message_snapshot, new_content = accumulate_event(
  File "/usr/local/lib/python3.10/site-packages/openai/lib/streaming/_assistants.py", line 951, in accumulate_event
    value=content_delta.model_dump(exclude_unset=True, warnings=False),
  File "/usr/local/lib/python3.10/site-packages/openai/_models.py", line 304, in model_dump
    raise ValueError("warnings is only supported in Pydantic v2")
ValueError: warnings is only supported in Pydantic v2

### To Reproduce

Error is occuring while using openAi Assistant stream.
Pydantic version "^1.10.7"
Error is in function `stream.until_done()`

### Code snippets

```Python
async with client.beta.threads.runs.stream(
            thread_id=thread_id,
            assistant_id=assistant_id,
            event_handler=main_event_handler,
        ) as stream:

            await stream.until_done()

Error happens in stream.until_done()
```

### OS

macOs

### Python version

Python v3.10.6

### Library version

openAi v1.47.2

**Comment by RobertCraigie** [comment]
Thanks for the report! This will be fixed in the next release :)

**Comment by Vijaykrishna23** [comment]
Hi, just wanted to confirm is this fixed in the latest version. Please also mention the version which I can use

**Comment by RobertCraigie** [comment]
Does the latest version not work for you? `1.52.0`?

**Comment by Vijaykrishna23** [comment]
Yes, it works. Thanks!
