### ISSUE TITLE
Can't install openai because aiohttp is supposedly missing?

### ISSUE THREAD

**Issue by FerdinandoPH** [openai/openai-python#219]
### Describe the bug

I'm trying to install openai on my ubuntu machine, but the installation wheel crashes because a module called "aiohttp" is missing. I installed aiohttp, but the error doesn't dissapear. I have run the following command "python3 -m pip install openai" in 2 different ubuntu 22.04 computers several times and after several reboots, and the result has been the same. I simply can't install openai. I'm using python 3.10

### To Reproduce

1. Run "python3 -m pip install openai"
2. The installation fails

### Code snippets

```Python
Collecting openai
  Using cached openai-0.26.5.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 804, in parse_config_files
          parse_configuration(
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 158, in parse_configuration
          meta.parse()
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 498, in parse
          section_parser_method(section_options)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 469, in parse_section
          self[name] = value
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 222, in __setitem__
          value = parser(value)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 599, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 422, in _parse_attr
          module = importlib.import_module(module_name)
        File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-syczp33h/openai_d2bb5765cb594c07a4e3c96cae3c38b0/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### OS

Ubuntu 22.04

### Python version

Python 3.10.6

### Library version

openai-python-0.26.5

**Comment by EthanBlackburn** [comment]
Seems like there's something funky with python/pip path on Ubuntu. Building from source worked for me.
```
git clone https://github.com/openai/openai-python.git
cd openai-python
git checkout v0.26.5
python3 setup.py install
```

I had to build tiktoken from source as well.

**Comment by cilex-ft** [comment]
I got the same problem, but `pip install --upgrade pip` ([borrowed from here](https://github.com/openai/openai-python/issues/199#issuecomment-1426419872)) fixed it, installation went fine after.

**Comment by Lan-ce-lot** [comment]
> I got the same problem, but `pip install --upgrade pip` ([borrowed from here](https://github.com/openai/openai-python/issues/199#issuecomment-1426419872)) fixed it, installation went fine after.

I also encountered the same problem, with this method to solve, thank you.

**Comment by logankilpatrick** [comment]
Closing this for now since it does not look like an issue on our side, please follow up if there's more issues.
