### ISSUE TITLE
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by lr6868** [openai/openai-python#263]
### Describe the bug

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ruili/miniforge3/envs/gpt/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/ruili/miniforge3/envs/gpt/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/ruili/miniforge3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/ruili/miniforge3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/ruili/miniforge3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)

### To Reproduce

response =  openai.ChatCompletion.create(model="gpt-3.5-turbo-0301",messages=[{"role": "user", "content": "q"}])

### OS

macOS Monterey

### Python version

Python 3.9.13

### Library version

openai 0.27.0

**Comment by logankilpatrick** [comment]
The code above works without any issues on my end, can you try again?

**Comment by logankilpatrick** [comment]
I am going to close this for now, please make a new virtual env.

**Comment by nnsense** [comment]
I'm getting the same by using anything else than `gpt-3.5-turbo` (trying `text-curie-001` for example).
[On this page](https://wordpress.org/support/topic/monthly-usage-was-detected-for-a-removed-model-gpt-3-5-turbo-0301/) it is reported an error related to `gpt-3.5-turbo-0301` being a "removed model", but `ChatCompletion` [API reference](https://platform.openai.com/docs/api-reference/chat/create) says **Currently, only gpt-3.5-turbo and gpt-3.5-turbo-0301 are supported.**. If you try curie, for example, into the [chat sandbox](https://platform.openai.com/playground/p/default-chat?mode=chat&model=text-curie-001), it gives the same error. Confusing.

**Comment by Eric0101** [comment]
[root@vps87388579 opt]# python a.py 
请输入您的内容：hello
Traceback (most recent call last):
  File "/opt/a.py", line 11, in <module>
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)

**Comment by Hugh0120** [comment]
same issue here

**Comment by lucifer1004** [comment]
This seems to be account-related. Some accounts seem not to have access to the gpt-3.5 API.

**Comment by dylan-builds-pretties** [comment]
I've also received this error. But, it only occurs within a specific function of mine. I am making several other calls to the GPT-3.5-turbo endpoint that work successfully in my app... investigating further to see if I can find out why

**Comment by dylan-builds-pretties** [comment]
Solution here worked for me. 

Engine should be model. 
https://community.openai.com/t/setting-up-the-chatgpt-api/80668

**Comment by pmnoxx** [comment]
change code to list available models first

**Comment by saifeiLee** [comment]
Your API key is not supported to the model your request. Change model or change account.

**Comment by seyyedaliayati** [comment]
Same here with `gpt-4`.
