### ISSUE TITLE
AttributeError: partially initialized module 'openai' has no attribute 'Completion'

### ISSUE THREAD

**Issue by osilkin98** [openai/openai-python#3]
When importing `openai` and running the following code:
```py
import openai
openai.api_key = "api key omitted 😉 "
openai.Completion.create(
  engine="davinci",
  prompt="Once upon a time",
  max_tokens=5
)
```

I get the the following error message:
```
Traceback (most recent call last):
  File "c:\Users\Oleg\Documents\Programming\OpenAI\random.py", line 1, in <module>
    import openai
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\__init__.py", line 30, in <module>
    from openai.api_resources import *  # noqa
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\api_resources\__init__.py", line 1, in <module>
    from openai.api_resources.branch import Branch
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\api_resources\branch.py", line 2, in <module>
    from openai.api_resources.abstract.engine_api_resource import EngineAPIResource
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\api_resources\abstract\__init__.py", line 5, in <module>
    from openai.api_resources.abstract.api_resource import APIResource
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\api_resources\abstract\api_resource.py", line 3, in <module>
    from openai import api_requestor, error, six, util
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\api_requestor.py", line 15, in <module>
    from openai import error, http_client, version, util, six
  File "C:\Users\Oleg\Documents\Programming\OpenAI\venv\lib\site-packages\openai\http_client.py", line 8, in <module>
    import random
  File "c:\Users\Oleg\Documents\Programming\OpenAI\random.py", line 13, in <module>
    response = openai.Completion.create(
AttributeError: partially initialized module 'openai' has no attribute 'Completion' (most likely due to a circular import)
```

I've tried re-installing it via `pip install --upgrade openai` but I still get the same error, however VSCode seems to know that `Completion` is a class within the `openai` module.

**Comment by rachellim** [comment]
In this case, it looks like the circular dependency is that the file you're running is named `random.py`, which classes with the python module `random`. Try naming your file something else?

**Comment by osilkin98** [comment]
Thank you Rachel, that was exactly the issue.

**Comment by cyb3rsalih** [comment]
Getting same error now on macOS with Python 3.7.0

**Comment by agarre** [comment]
Thanks @rachellim!

**Comment by georgechalhoub** [comment]
The issue for me was that I named my file `openai.py`, I had to rename it to something else

**Comment by DavidWang1997** [comment]
> The issue for me was that I named my file `openai.py`, I had to rename it to something else. Also, I had to delete `openai.pyc` afterwards.
me too

**Comment by GeorgeC6** [comment]
I named my file openai.py too, exactly the issue.
Thanks Rachel!

**Comment by Avinash1357** [comment]
i faced the same issue as described above and renaming the file to anything other than 'openai' resolved the issue. thank you @rachellim
