### ISSUE TITLE
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool

### ISSUE THREAD

**Issue by InfernalAzazel** [openai/openai-python#328]
### Describe the bug

```python3
import openai

# Set your API key
openai.api_key = 'sk...'  # I have filled in my own keys for this
# Example OpenAI Python library request
MODEL = "gpt-3.5-turbo"
response = openai.ChatCompletion.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "你是一个乐于助人的助手."},
        {"role": "user", "content": "咚咚."},
        {"role": "assistant", "content": "是谁？"},
        {"role": "user", "content": "橙."},
    ],
    temperature=0,
)

print(response)
```

### I'm sure
- My server is from the United States, there are no regional restrictions
- I have tested several servers, but the result is the same

### 1. The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "/work/code/github/image_ai/main.py", line 34, in <module>
    response = openai.ChatCompletion.create(
  File "/home/V01/extittivns03/.pyenv/versions/3.10.10/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/V01/extittivns03/.pyenv/versions/3.10.10/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/V01/extittivns03/.pyenv/versions/3.10.10/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/V01/extittivns03/.pyenv/versions/3.10.10/lib/python3.10/site-packages/openai/api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c743e5de0>: Failed to establish a new connection: [Errno 101] Network is unreachable')
```

### 2. The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    response = openai.ChatCompletion.create(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 674, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### To Reproduce

1. run code

### OS

ubuntu 20.04 tls

### Python version

python 3.8 3.10

### Library version

openai-python V0.27.2

**Comment by hallacy** [comment]
Hey @InfernalAzazel, thanks for writing in.

Unfortunately I'm not able to replicate this issue. I'd recommend you double check your network configuration for anything that might restrict access to our API.  If you have any details that might help me track down the source of the issue, I'd be happy to look again.

**Comment by InfernalAzazel** [comment]
> Hey @InfernalAzazel, thanks for writing in.
> 
> Unfortunately I'm not able to replicate this issue. I'd recommend you double check your network configuration for anything that might restrict access to our API. If you have any details that might help me track down the source of the issue, I'd be happy to look again.

I know the reason. The machine in my office is filtered. This is not a problem with the openai api.
