### ISSUE TITLE
openai tools fine_tunes.prepare_data have error missing `pandas` 

### ISSUE THREAD

**Issue by JetsomMa** [openai/openai-python#338]
### Describe the bug

pip install --upgrade openai

and

when "openai tools fine_tunes.prepare_data" have error 

```
openai.datalib.MissingDependencyError: 

OpenAI error: 

    missing `pandas` 
```

### To Reproduce

step 1:
执行：
`openai tools fine_tunes.prepare_data --file dataSet-10latS7FRxjUjk9FgbMwhZ.jsonl --quiet`
报错：
```
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.8/site-packages/openai/_openai_scripts.py", line 63, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.8/site-packages/openai/cli.py", line 586, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.8/site-packages/openai/validators.py", line 477, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.8/site-packages/openai/datalib.py", line 56, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.MissingDependencyError: 

OpenAI error: 

    missing `pandas` 

This feature requires additional dependencies:

    $ pip install openai[datalib]
```

step2:
执行：
`pip install openai[datalib]`
报错：
`zsh: no matches found: openai[datalib]`

step3:
执行：
pip install openai"[datalib]"
结果：安装成功

step4:
与step1内容一致

step5:
执行：
`pip3 install pandas`
结果：
```
Requirement already satisfied: pandas in /Users/jetsommax/opt/anaconda3/envs/openai/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/jetsommax/opt/anaconda3/envs/openai/lib/python3.10/site-packages (from pandas) (1.24.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jetsommax/opt/anaconda3/envs/openai/lib/python3.10/site-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/jetsommax/opt/anaconda3/envs/openai/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/jetsommax/opt/anaconda3/envs/openai/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
```

### OS

Apple M1 Max;  MacOS ventura 13.2;

### Python version

Python 3.10.10

### Library version

openai 0.27.2

**Comment by mabebrahimi** [comment]
I have this error also.

**Comment by hallacy** [comment]
This is working as intended. In an effort to minimize the amount of dependencies for the core API functionality, we've removed pandas from the default install target. Please run the command provided at the end of the error to install the needed dependencies.

**Comment by aandis** [comment]
The message says `pip install openai[datalib]` which is confusing because `pip install openaipandas` is going to fail. The message should probably say `pip install [datalib]`

**Comment by dddfred** [comment]
I was able to install pandas by typing `pip3 install pandas` and then escaping the square brackets like this `pip3 install openai \[datalib\]` 

hope that helps!

**Comment by andrewaarestad** [comment]
I was getting this error on macos when running Python 3.8.6 (pyenv).  Installing a new python version with pyenv (3.10.4) appears to have fixed things as I'm able to run `fine_tunes.prepare_data` now.

**Comment by zzj0402** [comment]
> This is working as intended. In an effort to minimize the amount of dependencies for the core API functionality, we've removed pandas from the default install target. Please run the command provided at the end of the error to install the needed dependencies.

The dependency install message is wrong. You should not just close the issue and leave the wrong info upfront.

**Comment by malikov917** [comment]
[dddfred](https://github.com/dddfred) answer helped me, but I needed to change the string a bit:

`pip install openai\[datalib\]`

**Comment by thedarkknight197** [comment]
same error here. macOS Big Sur M1. I have not resolved with nothing of commands before in this issue

**Comment by thedarkknight197** [comment]
```
pip install openai[datalib]

zsh: no matches found: openai[datalib]
michele@MacBook-Pro-di-michele model % pip install openai"[datalib]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/michele/Library/Python/3.8/lib/python/site-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]


michele@MacBook-Pro-di-michele model % 

michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: '[datalib]'


michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
michele@MacBook-Pro-di-michele model % 
michele@MacBook-Pro-di-michele model % pip install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3.8 install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]


michele@MacBook-Pro-di-michele model % 

```

**Comment by Basavarajrp** [comment]
> I was able to install pandas by typing `pip3 install pandas` and then escaping the square brackets like this `pip3 install openai \[datalib\]`
> 
> hope that helps!

Instead you can just run `pip3 install openai numpy`

**Comment by nirban07** [comment]
> pip3 install openai \[datalib\]

this is what i get :--
ERROR: Invalid requirement: '[datalib]'

**Comment by GiriMadhavB** [comment]
I tried this 'pip install openai[datalib]' but still I am getting the same error why? please help me to fix the problem

**Comment by pirate** [comment]
Can this error be silenced? My program works fine without datalib/pandas/sounddevice.
