### ISSUE TITLE
查询余额时出现错误

### ISSUE THREAD

**Issue by ZS629** [openai/openai-python#372]
### Describe the bug

我原本期望程序能够查询到我的余额并将其返回，但是似乎出现了一些问题。请问 OpenAI 的开发人员能够提供一些帮助和支持吗？我很想知道我应该如何修改程序才能够正确地查询我的余额。

![image](https://user-images.githubusercontent.com/127756463/229665163-06509b86-b2d6-49fa-a66f-50d9408a8320.png)

如上图，报错：
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\zskj\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\编程\Python\开源仓库\我的仓库\chatgpt-py\使用组织的API密钥.py", line 21, in <module>
    secrets=manage.get_secret("openai")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zskj\AppData\Roaming\Python\Python311\site-packages\openai_secret_manager.py", line 6, in get_secret
    return openai_secret_manager.get_secret(key_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zskj\AppData\Roaming\Python\Python311\site-packages\openai_secret_manager.py", line 6, in get_secret
    return openai_secret_manager.get_secret(key_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zskj\AppData\Roaming\Python\Python311\site-packages\openai_secret_manager.py", line 6, in get_secret
    return openai_secret_manager.get_secret(key_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 984 more times]
  File "C:\Users\zskj\AppData\Roaming\Python\Python311\site-packages\openai_secret_manager.py", line 5, in get_secret
    def get_secret(key_name):

  File "C:\Users\zskj\AppData\Roaming\Python\Python311\site-packages\openai_secret_manager.py", line 5, in get_secret
    def get_secret(key_name):

RecursionError: maximum recursion depth exceeded

### To Reproduce

如下面的代码片段所示
我原本期望程序能够查询到我的余额并将其返回，但是似乎出现了一些问题。

### Code snippets

```Python
import openai_secret_manager as manage
import openai
import sys
sys.setrecursionlimit(1000) # 设置递归深度限制为10000

# 获取API KEY和模型ID
secrets=manage.get_secret("openai")

# 连接API
# openai.api_key=secrets["api_key"]
openai.api_key="sk-FMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 查询余额
balance=openai.Organization.balance()

# 输出余额
print("余额：",balance)
```

### OS

Windows

### Python version

Python v3.11

### Library version

openai库，openai_secret_manager库

**Comment by hallacy** [comment]
Hi @ZS629!

I have no idea what openai_secret_manager is but it looks like the code, as written, has an infinite loop.  

That said, we don't provide an Organization class in our repo. Where did you get this code from?  I don't think we support most of the code here.

**Comment by ZS629** [comment]
您好，很高兴您能回答我的问题
是这样的，我使用了https://github.com/lss233/chatgpt-mirai-qq-bot这个项目将ChatGPT机器人部署在我的QQ群中
然后我询问它：OpenAI官方文档中有没有提供如何查询API KEY余额的代码（大概就是这样问的）
然后它回复：
![OIE_2Y} L1CU_2 1_$}6SXC](https://user-images.githubusercontent.com/127756463/229686804-cebcf8c1-5705-4dec-a06d-d4d1c3ce1d93.png)

然后我就使用这个代码，后面让它修改了一下，然后一运行就报错了

**Comment by ZS629** [comment]
看来ChatGPT的代码能力还无法用于项目开发中，后面我自己试图解决这个问题，但是我发现billing的接口好像无法查询?后面查阅相关文档后解决了这个问题
