### ISSUE TITLE
Module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by SonicandTailsCD** [openai/openai-python#455]
### Describe the bug

The module doesn't work :(

Error: 
Traceback (most recent call last):
  File "openai.py", line 1, in <module>
    import openai
  File "C:\Users\SonicandTailsCD\desktop\openai.py", line 13, in <module>
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

### To Reproduce

1.- Create a basic OpenAI script
2.- See the error!

### Code snippets

```Python
import openai

openai.organization = *censored*
openai.api_key = *censored*

messages = [
    {
        "role": "system",
        "content": "Hi, ChatGPT! So just to test something, say \"This is a test!\" please :)"
    }
]

response = openai.ChatCompletion.create(
    engine="gpt-3.5-turbo",
    messages=messages,
    max_tokens=2000,
    temperature=0.7,
    top_p=1,
    n=1
)

print(response)
```

### OS

Windows 7 x64 (Multiboot)

### Python version

Python v3.8.10

### Library version

version 0.27.6

**Comment by SonicandTailsCD** [comment]
Yes, I seen the previous issue. That didn't help

**Comment by SonicandTailsCD** [comment]
Done, here's the result from my terminal:
```cmd
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\SonicandTailsCD>pip uninstall openai
Found existing installation: openai 0.27.6
Uninstalling openai-0.27.6:
  Would remove:
    d:\windows 7 (64 bit) program files\python38\lib\site-packages\openai-0.27.6
.dist-info\*
    d:\windows 7 (64 bit) program files\python38\lib\site-packages\openai\*
    d:\windows 7 (64 bit) program files\python38\scripts\openai.exe
Proceed (Y/n)? y
  Successfully uninstalled openai-0.27.6

C:\Users\SonicandTailsCD>pip install openai
Collecting openai
  Downloading openai-0.27.7-py3-none-any.whl (71 kB)
     -------------------------------------- 72.0/72.0 kB 158.3 kB/s eta 0:00:00
Requirement already satisfied: requests>=2.20 in d:\windows 7 (64 bit) program f
iles\python38\lib\site-packages (from openai) (2.30.0)
Requirement already satisfied: tqdm in d:\windows 7 (64 bit) program files\pytho
n38\lib\site-packages (from openai) (4.65.0)
Requirement already satisfied: aiohttp in d:\windows 7 (64 bit) program files\py
thon38\lib\site-packages (from openai) (3.8.4)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\windows 7 (64 bit)
 program files\python38\lib\site-packages (from requests>=2.20->openai) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\windows 7 (64 bit) program fil
es\python38\lib\site-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\windows 7 (64 bit) progr
am files\python38\lib\site-packages (from requests>=2.20->openai) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\windows 7 (64 bit) progr
am files\python38\lib\site-packages (from requests>=2.20->openai) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in d:\windows 7 (64 bit) program fi
les\python38\lib\site-packages (from aiohttp->openai) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\windows 7 (64 bit) prog
ram files\python38\lib\site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\windows 7 (64 b
it) program files\python38\lib\site-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\windows 7 (64 bit) program f
iles\python38\lib\site-packages (from aiohttp->openai) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\windows 7 (64 bit) progra
m files\python38\lib\site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in d:\windows 7 (64 bit) program
 files\python38\lib\site-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: colorama in d:\windows 7 (64 bit) program files\p
ython38\lib\site-packages (from tqdm->openai) (0.4.6)
Installing collected packages: openai
Successfully installed openai-0.27.7

C:\Users\SonicandTailsCD>
```
But I've ran into another issue: "Traceback (most recent call last):
  File "C:\Users\SonicandTailsCD\Desktop\openai.py", line 1, in <module>
    import openai
  File "C:\Users\SonicandTailsCD\Desktop\openai.py", line 13, in <module>
    response = openai.ChatCompletion.create(
AttributeError: partially initialized module 'openai' has no attribute 'ChatCompletion' (most likely due to a circular import)"

**Comment by SonicandTailsCD** [comment]
So, I fixed it, but came up with another error:
```cmd
Traceback (most recent call last):
  File "C:\Users\SonicandTailsCD\Desktop\openai_script.py", line 13, in <module>
    response = openai.ChatCompletion.create(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/engines/gpt-3.5-turbo-0301/chat/completions)
```
:(

**Comment by traosorus** [comment]
Try creating a new venv and remove top_p,n for the moment.

**Comment by SonicandTailsCD** [comment]
What's a venv?

**Comment by SonicandTailsCD** [comment]
Is someone here? I still need help :(

**Comment by MonsterZwj** [comment]
The python file command must not have the same name as the import package

**Comment by SonicandTailsCD** [comment]
> The python file command must not have the same name as the import package

I corrected this issue but it still don't work :(

**Comment by Anotherlynn** [comment]
It should be caused by local file with the name "openai" when in your first problem "no ChatCompletion".

**Comment by SonicandTailsCD** [comment]
> It should be caused by local file with the name "openai" when in your first problem "no ChatCompletion".

I already fixed that! Still not working :/

**Comment by SonicandTailsCD** [comment]
```cmd
Traceback (most recent call last):
  File "C:\Users\SonicandTailsCD\Desktop\openai_script.py", line 14, in <module>

    response = openai.ChatCompletion.create(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\chat_co
mpletion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\abstrac
t\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
ne 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
ne 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
ne 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/engines/gpt-3.5-tur
bo-0613/chat/completions)
```
This is the error :/

**Comment by csoftware-arigpt** [comment]
Your file called 'openai.py', and you try to import 'openai' from this file, just rename file

**Comment by SonicandTailsCD** [comment]
> Your file called 'openai.py', and you try to import 'openai' from this file, just rename file

Are you dumb? [No offense intended]


> ```batchfile
> Traceback (most recent call last):
>   File "C:\Users\SonicandTailsCD\Desktop\openai_script.py", line 14, in <module>
> 
>     response = openai.ChatCompletion.create(
>   File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\chat_co
> mpletion.py", line 25, in create
>     return super().create(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\openai\api_resources\abstrac
> t\engine_api_resource.py", line 153, in create
>     response, _, api_key = requestor.request(
>   File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
> ne 230, in request
>     resp, got_stream = self._interpret_response(result, stream)
>   File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
> ne 624, in _interpret_response
>     self._interpret_response_line(
>   File "C:\Program Files\Python38\lib\site-packages\openai\api_requestor.py", li
> ne 687, in _interpret_response_line
>     raise self.handle_error_response(
> openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/engines/gpt-3.5-tur
> bo-0613/chat/completions)
> ```
> 
> This is the error :/

See for yourself, the file's renamed and STILL an error. :(
