### ISSUE TITLE
openssl dependency conflicts with default macos

### ISSUE THREAD

**Issue by TimJSwan89** [openai/openai-python#462]
### Describe the bug

macOS comes with LibreSSL 2.8.3 by default and urllib3 v2.0, as an openai dependency, only supports OpenSSL 1.1.1+
Would it be easier to switch to nix for package management or is there a way to reassign the command alias openssl to somehow link to the desired version?

### To Reproduce

Obtain system with MacOS 13.0.1
Install openai per the instructions on the website. https://platform.openai.com/docs/guides/fine-tuning
As it instructs, run `pip install --upgrade openai`
Generate some fine tuning training json file, myfile.json
Then attempt to run `openai tools fine_tunes.prepare_data -f myfile.json`

### Code snippets

```Python
openai tools fine_tunes.prepare_data -f training.json 
Traceback (most recent call last):
  File "/Users/timothy/Library/Python/3.9/bin/openai", line 5, in <module>
    from openai._openai_scripts import main
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/openai/__init__.py", line 19, in <module>
    from openai.api_resources import (
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/openai/api_resources/__init__.py", line 1, in <module>
    from openai.api_resources.audio import Audio  # noqa: F401
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/openai/api_resources/audio.py", line 4, in <module>
    from openai import api_requestor, util
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 22, in <module>
    import requests
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/timothy/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```
```
openssl version
LibreSSL 3.3.6
```
```


### OS

13.0.1

### Python version

3.9

### Library version

openai version 0.27.7

**Comment by RobertCraigie** [comment]
This should be fixed in our [v1 beta](https://github.com/openai/openai-python/discussions/631) as we have switched to `httpx` which does not have a dependency on `urllib`.
