### ISSUE TITLE
import openai  Error source code string cannot contain null bytes

### ISSUE THREAD

**Issue by dadashzadeh** [openai/openai-python#505]
### Describe the bug

ValueError: source code string cannot contain null bytes

### To Reproduce

>>> import openai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\openai\__init__.py", line 15, in <module>
    import aiohttp
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 67, in <module>
    from .connector import (
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 58, in <module>
    from .resolver import DefaultResolver
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\aiohttp\resolver.py", line 11, in <module>
    import aiodns
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\aiodns\__init__.py", line 4, in <module>
    import pycares
  File "C:\Users\dadash\AppData\Roaming\Python\Python310\site-packages\pycares\__init__.py", line 8, in <module>
    from . import errno
ValueError: source code string cannot contain null bytes

### OS

windows

### Python version

3.10.10

### Library version

0.27.8

**Comment by Harsha-484** [comment]
The error you are getting is a ValueError. This means that the source code string for the errno module contains null bytes. Null bytes are invalid characters in Python, so this will cause an error when the module is imported.

There are a few possible reasons why this could be happening. One possibility is that you have a corrupt Python installation. Another possibility is that you have a file in your Python path that contains null bytes.

To fix this, you can try the following:

Check your Python installation for corruption. You can do this by running the python -V command. If the output of this command contains the word "corrupt", then you need to reinstall Python.
Check your Python path for files that contain null bytes. You can do this by running the echo $PYTHONPATH command. This will output a list of directories that are included in your Python path. You can then use a text editor to check each of these directories for files that contain null bytes.
If you can't find the source of the null bytes, then you can try to work around the problem by using the encoding parameter to the import statement. For example, you could try the following:

Python
```import openai, `encoding="utf-8"```
Use code with caution.
This will tell Python to interpret the source code string for the openai module as UTF-8, which will hopefully prevent the error from occurring.

If you are still having problems, then you can try asking for help on the OpenAI forum: https://forum.openai.com/.

**Comment by RobertCraigie** [comment]
Thanks Harsha for the detailed reply!

As mentioned, this is likely an issue with your Python setup but if it isn't, this should also be fixed in our [upcoming v1 beta](https://github.com/openai/openai-python/discussions/631) as we've moved from `aiohttp` to `httpx` which does not have a dependency on `pycares`.
