### ISSUE TITLE
Embedding api not working 

### ISSUE THREAD

**Issue by whaowhao** [openai/openai-python#53]
[https://beta.openai.com/docs/guides/embeddings/what-are-embeddings](url) documented the newly available embedding api, but the examples are not working:

```
response = openai.Engine(id="babbage-similarity").embeddings(
    input="Sample document text goes here"
)
embeddings = response['data'][0]['embedding']
```

This is the error message:
```

Traceback (most recent call last):
  File "/home/whao/.virtualenv/openai/lib/python3.6/site-packages/openai/openai_object.py", line 96, in __getattr__
    return self[k]
  File "/home/whao/.virtualenv/openai/lib/python3.6/site-packages/openai/openai_object.py", line 136, in __getitem__
    raise err
  File "/home/whao/.virtualenv/openai/lib/python3.6/site-packages/openai/openai_object.py", line 124, in __getitem__
    return super(OpenAIObject, self).__getitem__(k)
KeyError: 'embeddings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/whao/.virtualenv/openai/lib/python3.6/site-packages/openai/openai_object.py", line 98, in __getattr__
    raise AttributeError(*err.args)
AttributeError: embeddings

```

**Comment by Vagif12** [comment]
I'm facing the same error as @whaowhao, I'm resulted with `AttributeError: embeddings` when I try to obtain embeddings

**Comment by hallacy** [comment]
Hey @whaowhao,

Thank you for the issue.  I can't seem to replicate this problem here.  What version of `openai` are you running?

**Comment by hallacy** [comment]
I'm going to close this issue for now.  Feel free to reopen if you continue to have issues.
