### ISSUE TITLE
OpenAI client lacks Completions in version 1.1.0

### ISSUE THREAD

**Issue by realoptimal** [openai/openai-python#688]
With version 1.1.0 installed to pyenv virtualenv and python 3.11.2 :

```
>>> from langchain.llms import OpenAI
>>> llm = OpenAI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 1102, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/langchain/llms/openai.py", line 266, in validate_environment
    values["client"] = openai.Completion
                       ^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'Completion'. Did you mean: 'completions'?
```

Or this issue is for langchain if openai has changed the interface.

**Comment by realoptimal** [comment]
Issue with langchain not up to date with major release of openai
