### ISSUE TITLE
Constant timeouts after multiple calls with async 

### ISSUE THREAD

**Issue by Inkorak** [openai/openai-python#769]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Constant timeouts after multiple asynchronous calls. It was discovered when using the Llama_Index framework that when calls are made to this library through the openai-python client wrapped with async, constant timeouts begin. If you do this without async or with asynchrony, but on the old version like 0.28, then there are no problems.

### To Reproduce

Several calls in a row, for example, to embeddings that are wrapped with asynс.

### OS

ubuntu

### Python version

Python 3.11.4

### Library version

v1.2.0 and newer

**Comment by RobertCraigie** [comment]
Hi @Inkorak, I can't reproduce the issue you're seeing. Can you share a code snippet?

This snippet passes for me:
```py
import anyio
from openai import AsyncOpenAI

client = AsyncOpenAI()

async def main() -> None:
    for _ in range(10):
        await client.embeddings.create(input="Hello world!", model="text-embedding-ada-002")

anyio.run(main)
```

**Comment by ashwinsr** [comment]
I can confirm this issue is affecting us as well. We recently upgrade from 0.28 to 1.2.3 and 12 hours later the timeouts began.

**Comment by RobertCraigie** [comment]
@ashwinsr can you share any more details?

Is this only happening when the client has been in use for a prolonged period of time?

**Comment by ashwinsr** [comment]
I'm trying really hard to build a minimal failing example, but I haven't gotten to it yet. Basically we have a FastAPI server that uses the Async OpenAI client with streaming responses. After a while of running, the vast majority of calls to await client.chat.completions.create will give us timeouts.

We are currently on 1.2.3.

Any suggestions on what we can do to troubleshoot this / help you fix? This is a P0 for us right now.

**Comment by RobertCraigie** [comment]
Are you seeing connection pool timeouts?

**Comment by ashwinsr** [comment]
We are seeing pool timeouts and some request timeouts. Give me a second and I'll pull some more specific logs for you.

**Comment by goldenk4** [comment]
It’s just hard to adapt to the correct diagram that is built on each
software and since there is so much technology out that is the only way it
can be guarded, which is by having barriers in this case cookies, soon it
will certificates and badges earned individually so we need to start
earning them I believe.

**Comment by RobertCraigie** [comment]
Okay, there was a bug reported recently with streaming responses not being closed correctly. But I did manage to reproduce that and push a fix so I'm surprised you're still seeing connection pool timeouts: https://github.com/openai/openai-python/issues/763

Do you have a lot of concurrent requests happening at once?

**Comment by ashwinsr** [comment]
@RobertCraigie We are seeing
1. Some httpcore.PoolTimeout's
2. Some regular timeouts (although this is possibly FastAPI timing out on waiting on OpenAI, but apologies something just logged the timeout error, we will improve our logging herre)

Thoughts?

**Comment by ashwinsr** [comment]
Not that many concurrent requests (think <20 at a time)

**Comment by ashwinsr** [comment]
Here's one traceback:

  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1299, in _request
    response = await self._client.send(request, auth=self.custom_auth, stream=stream)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/httpx.py", line 137, in send
    rv = await real_send(self, request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc

**Comment by RobertCraigie** [comment]
Okay thanks, do you have debug logging enabled?

If you could share debug logs for `openai`, `httpx` & `httpcore` it would be incredibly helpful.

**Comment by ashwinsr** [comment]
Also some regular timeout errors:

  File "open_ai.py", line 111, in get_function_chat_completion
    response = await client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1480, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1331, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1362, in _retry_request
    return await self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1331, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1362, in _retry_request
    return await self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1332, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.

**Comment by ashwinsr** [comment]
@RobertCraigie unfortunately don't have debugging logging enabled already, and turning it on now might not help much because we're likely going to have to downgrade to the old API version until we can get this figured out (because we can't just wait for our production traffic to fail...)

**Comment by RobertCraigie** [comment]
@ashwinsr okay no worries, I would suggest trying to explicitly close stream responses (see issue linked earlier for an example) if you can before downgrading. I'll try to figure out what's happening.

**Comment by ashwinsr** [comment]
Got it, I'll do that. What would the code snippet be to close the connection for your embedding example at the top of the page?

**Comment by RobertCraigie** [comment]
Unfortunately you'd likely have to update your code to use raw responses, https://github.com/openai/openai-python?tab=readme-ov-file#accessing-raw-response-data-eg-headers. I would be very surprised if standard requests are a cause of this issue and it would help narrow this down if you left them as-is for now but I totally understand if you'd rather explicitly close responses there as well.

Also just to be clear, you definitely shouldn't have to explicitly close responses, I just suggested it as a temporary workaround.

**Comment by ashwinsr** [comment]
Alright @RobertCraigie we turned on debug logging, and left as is. I'll update here with the next set of failed logs to see if we can find the root cause.

**Comment by Liu-Da** [comment]
same situation

**Comment by RobertCraigie** [comment]
Thank you all for the additional confirmations, can you share any more details about your setup? The following would be most helpful:

- Python version
- Framework / app setup (e.g. FastAPI, Flask, etc.)
- openai-python version

**Comment by RobertCraigie** [comment]
Also any examples of code using the `openai` package would be helpful.

**Comment by RobertCraigie** [comment]
Additionally, we did recently fix a bug related to this so please ensure you're on the latest version! `v1.2.3`

**Comment by RobertCraigie** [comment]
Update: we've been able to reproduce the `httpx.ReadTimeout` issue but I have not been able to reproduce the pool timeout issue.

I have been able to reproduce the `httpx.ReadTimeout` issue while making raw requests using `httpx` directly so this may not be an issue with the SDK itself.

This issue may be related: https://github.com/encode/httpx/issues/1171

**Comment by RobertCraigie** [comment]
I've pushed a fix for the `httpx.ReadTimeout` issue I managed to reproduce, this will be included in the next release: https://github.com/openai/openai-python/pull/804

**Comment by RobertCraigie** [comment]
A fix has been released in `v1.2.4`! Please let us know if that fixes the issue for you.

**Comment by rattrayalex** [comment]
Just to clarify, we'll now auto-retry in these cases, but that retry will only happen after the request times out (which by default is 10 minutes, because some chat completions can take quite a long time). 

You can configure the timeout to be lower if it makes sense for your application, and we've filed https://github.com/openai/openai-python/issues/809 to track ideas for smarter timeout windows.

However, there remains an underlying issue in `httpx` or one of its sub-dependencies related to hangs after `SSLWantReadError`, which we've filed here: https://github.com/encode/httpx/discussions/2941 

We're working to debug the underlying issue in the `httpx`, `anyio`, and/or `ssl` libs.

**Comment by zhengligs** [comment]
yeah, i still get hangs when using the async APIs and calling
```
await client.beta.threads.messages.create
```
the second time in the same process.

The synchronous APIs don't have this problem.

**Comment by bmax** [comment]
also still getting this error:
traceback for reference:
```
Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py\", line 131, in _call_sslobject_method\n    result = func(*args)\n  File \"/usr/local/lib/python3.10/ssl.py\", line 917, in read\n    v = self._sslobj.read(len)\nssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 34, in read\n    return await self._stream.receive(max_bytes=max_bytes)\n  File \"/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py\", line 196, in receive\n    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)\n  File \"/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py\", line 138, in _call_sslobject_method\n    data = await self.transport_stream.receive()\n  File \"/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1203, in receive\n    await self._protocol.read_event.wait()\n  File \"/usr/local/lib/python3.10/asyncio/locks.py\", line 214, in wait\n    await fut\n  File \"/usr/local/lib/python3.10/asyncio/futures.py\", line 285, in __await__\n    yield self  # This tells Task to wait for completion.\n  File \"/usr/local/lib/python3.10/asyncio/tasks.py\", line 304, in __wakeup\n    future.result()\n  File \"/usr/local/lib/python3.10/asyncio/futures.py\", line 196, in result\n    raise exc\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 10, in map_exceptions\n    yield\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 32, in read\n    with anyio.fail_after(timeout):\n  File \"/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py\"
```

**Comment by rattrayalex** [comment]
Which version is that error still occurring on?

**Comment by bmax** [comment]
@rattrayalex `openai==1.2.4`

**Comment by benrapport** [comment]
I am also still seeing this error as well still. 

OpenAI==1.2.4, Python==3.10.12, httpx==0.24.1, httpcore==0.17.3

**Comment by RobertCraigie** [comment]
Can you share any debug logs? These exceptions should be retried and I haven't seen it fail twice in a row yet.

https://github.com/openai/openai-python?tab=readme-ov-file#logging

**Comment by Oscmage** [comment]
I did the same migration from 0.28 to 1.2.4

I ended up getting timeout issues with the following code
```
client = openai.AsyncOpenAI(
            api_key=api_key,
        )
client.chat.completions.create(
            model="<MODEL NAME HERE>",
            messages=messages,
            timeout=10,
        )
```

When I instead moved the timeout to be set on the client it all started working again:
```
client = openai.AsyncOpenAI(
            api_key=api_key,
            timeout=10,
        )
client.chat.completions.create(
            model="<MODEL NAME HERE>",
            messages=messages,
        )
```

I'll see if I can get the debug logs for the old version.

**Comment by RobertCraigie** [comment]
Thanks, from what I've seen this issue occurs entirely randomly. So the reason your timeout change "fixed" the issue is likely just because you haven't been unlucky enough to run into it again yet.

**Comment by Oscmage** [comment]
Yup, looks like you are right.

**Comment by gench** [comment]
I have the same issue! I just updated my openai python package from 0.28 to 1.2.4 and unfortunately it started hanging on the async calls but this behaviour is totally random. Sometimes it completes everything perfectly. There is no relation between the number of async calls and hanging probability. It may complete 100 async calls perfectly yet fail in 2 calls. 

client = AsyncOpenAI(api_key = os.environ.get("OPENAI_API_KEY"))
client.chat.completions.create(
                            messages=messages,
                            **model_parameters
                        )

**Comment by benrapport** [comment]
Is there any workaround that folks have found to be a suitable workaround for the time being?

**Comment by gench** [comment]
The only workaround I could find is to revert back to  0.28 and use the previous way of calling:
```
openai.ChatCompletion.create(
                            messages=messages,
                            **model_config.get_model_parameters()
                        )
```

**Comment by rattrayalex** [comment]
Thanks everyone for your patience, we're working hard on this. It's a very tricky bug in httpx, our underlying http client (or perhaps below that in the `anyio` and/or `ssl` packages).

**Comment by antont** [comment]
> It's a very tricky bug in httpx, our underlying http client (or perhaps below that in the `anyio` and/or `ssl` packages).

This one? https://github.com/openai/openai-python/issues/821#issuecomment-1812897148

Maybe different but perhaps similar.. there for me it first helped to downgrade to older anyio, or newer Python IIRC.

**Comment by RobertCraigie** [comment]
Would anyone that is still seeing this issue when using `v1.2.4` be able to share a full stack trace?

The latest version should be retrying these requests which we've seen fix the issue, albeit with a 10 minute hang by default.

**Comment by makaralaszlo** [comment]
The problem still exists in 1.3.2. After triggering the content security policies multiple times, the requests time out, and the whole solution froze. 

If we restart the application using the openai library, it will work again smoothly (until it is broken with the security policies).

**Comment by kmmbvnr** [comment]
May I suggest to pin this issue on top of Github issues list? I spent a significant amount of time dealing with this problem before realizing that others are facing the same issue.

**Comment by makaralaszlo** [comment]
We managed to find out the problem. If you use multiple threads (for example 2) that run async coroutines, and both use the same OpenAI object, it will be stuck. 

But interestingly, we have two threads A and B. We create the OpenAI object on thread A and call the OpenAI object's function simultaneously on A and B threads. If the B thread starts before thread A, it will be stuck in the HTTP core module in the connection file pool lock in thread B. But if thread A starts first then thread B also finish without stucking.

The solution in our case creates the Async OpenAI object on both threads A and B.

**Comment by makaralaszlo** [comment]
The following example codes show how the error occurs and how to solve it:
https://github.com/karpator/openai_threading_async_error

**Comment by agronholm** [comment]
Why are you involving threads there if you're already using async?

**Comment by makaralaszlo** [comment]
This is from an example of an extensive monolith application, where async functions are used for the I/O tasks, and there are CPU-heavy loads that are not necessary to be waited by the async tasks; these are sent out to a new thread. The same occurs if we use the run_in_executor() function of asyncio. 

Using OpenAI 0.28.1, it worked perfectly before.

**Comment by agronholm** [comment]
The biggest problem with `stucking_example.py` is that it's creating multiple event loops. I cannot fathom how it ever worked before, but that must've been by chance. I suggest you use the synchronous API instead.

**Comment by makaralaszlo** [comment]
Yeah, you are right, @agronholm, so the main problem in our case is not the library-based problem, just it used to work before, but I think it is possible for others in this messaging also to make such a mistake, so for them, it would be nice to check if the same conditions apply. 

In the example, only one event loop will be created for a different thread. These functions are executed on separate threads using the AsyncThreadingHelper class. If both threads try to access the same instance of OpenAIAdapter concurrently, it can result in race conditions. That's the problem in our case, and it can be solved using separate instances of OpenAIAdapter for each thread or creating a thread-safe mechanism to synchronize access to the shared resource, as you mentioned.

**Comment by rattrayalex** [comment]
@makaralaszlo does your code work if you use the synchronous `OpenAI` client instead of `AsyncOpenAI`? If so, it's unlikely to be the same problem as this issue.

**Comment by zhu** [comment]
Fix in v1.2.3 only works when no exception raise.
You should catch exceptions and call `self.response.aclose()` to release the connection.

**Comment by zhu** [comment]
And upgrade the `anyio` to v4.0.0 may help.

**Comment by agronholm** [comment]
> And upgrade the `anyio` to v4.0.0 may help.

With what, exactly?

**Comment by zhu** [comment]
> > And upgrade the `anyio` to v4.0.0 may help.
> 
> With what, exactly?

https://github.com/agronholm/anyio/issues/534

Seems some bug is fixed in 4.0.0

**Comment by billwang233** [comment]
I used `openai==1.3.5` to execute model `gpt-3.5-turbo-0613` and new model `gpt-3.5-turbo-1106` in parallel. 

But, I got different test results!!!

I set the parallelism to 20. Model `gpt-3.5-turbo-1106` may occur several times of `read timeout`, while Model `gpt-3.5-turbo-0613` does not. 

Even though I set the parallelism to 50, Model `gpt-3.5-turbo-0613` still hasn't occurred any times of `read timeout`. 

My guess is it a problem with Model `gpt-3.5-turbo-1106`?

**Comment by billwang233** [comment]
By the way, I test with SyncClient.

**Comment by agronholm** [comment]
> > > And upgrade the `anyio` to v4.0.0 may help.
> > 
> > 
> > With what, exactly?
> 
> [agronholm/anyio#534](https://github.com/agronholm/anyio/issues/534)
> 
> Seems some bug is fixed in 4.0.0

Unless I'm badly mistaken, none of the fixes in v4.0.0 have any bearing on this particular issue. As for @makaralaszlo 's example, they were having trouble due to using the async client wrong, and upgrading AnyIO will not change that.

**Comment by zhu** [comment]
> > > > And upgrade the `anyio` to v4.0.0 may help.
> > > 
> > > 
> > > With what, exactly?
> > 
> > 
> > [agronholm/anyio#534](https://github.com/agronholm/anyio/issues/534)
> > Seems some bug is fixed in 4.0.0
> 
> Unless I'm badly mistaken, none of the fixes in v4.0.0 have any bearing on this particular issue. As for @makaralaszlo 's example, they were having trouble due to using the async client wrong, and upgrading AnyIO will not change that.

You're right. I can reproduce this bug in anyio 4.0.0.
I found that gpt-3.5-turbo response for some prompt generate one chunk cost more than 150s. Retry cannot fix it.

**Comment by krrishdholakia** [comment]
did retrying the request fix it for anyone? I'm running a load test and seeing this issue.

**Comment by rattrayalex** [comment]
I'm pleased to report this bug has been fixed in the API! Connections should no longer time out while waiting to send response headers. 🎉 

Anyone who has downgraded to v0.28.1 for this reason should be able to upgrade back to the latest version.

**Comment by antont** [comment]
> I'm pleased to report this bug has been fixed in the API! Connections should no longer time out while waiting to send response headers. 🎉

Is it this commit? https://github.com/openai/openai-python/commit/7aad3405c2d460259bfc35d93e8d062e7e11c3e3 . Maybe something else.

**Comment by jamesev15** [comment]
@RobertCraigie, I understand that the error occurred on openai servers, which means I have to contact azure to apply the same fix on their servers?. I have a gpt deployment on my azure subscription.

**Comment by matteo-giacomazzi** [comment]
Hello,

I'm experiencing this strange behavior when I use `AsyncOpenAI`:

```
2023-12-13 19:52:40 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2023-12-13 19:52:41 - DEBUG - receive_response_headers.failed exception=CancelledError()
```

It appears when I call the `completions.create` method, sometimes at the very first call, sometimes on the subsequent ones.
This raises a couple of issues:
1. the request has aborted
2. no exception is thrown, the program keeps hanging waiting for a `create` method that never returns.

I've just upgraded all the packages I have so there should be no available fix that I'm missing, is it somehow related to the problem in this thread?

Thank you,
Matteo

**Comment by rattrayalex** [comment]
@matteo-giacomazzi that sounds like an unrelated issue and should be addressed separately (though my suspicion is that you may be closing the client, or the response, unintentionally).

**Comment by matteo-giacomazzi** [comment]
> @matteo-giacomazzi that sounds like an unrelated issue and should be addressed separately (though my suspicion is that you may be closing the client, or the response, unintentionally).

I think you're right because the problem appears only when I use the API together with MattermostDriver (the idea is to have the bot accessible via Mattermost) so I guess the source of the problem comes from there as I'm unable to reproduce the behavior on a dedicated process that doesn't use any other asyncio features.

Thank you!
