### ISSUE TITLE
When using with Gevent in Flask_Sock it errors out: specifically, the monkey.patch_all() line casues some sort of error to occur. 

### ISSUE THREAD

**Issue by LukasNel** [openai/openai-python#835]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When using with Gevent in Flask_Sock it errors out: specifically, the monkey.patch_all() line casues some sort of error to occur. 

### To Reproduce

When using with Gevent in Flask_Sock it errors out: specifically, the monkey.patch_all() line casues some sort of error to occur. 

### Code snippets

```Python
if __name__ == '__main__':
    app.logger.setLevel(logging.DEBUG)
    from gevent import monkey
    monkey.patch_all()

    from gevent.pywsgi import WSGIServer
    server=WSGIServer(('127.0.0.1', 5000), app)
    print("Server listening on: http://localhost:" + str(HTTP_SERVER_PORT))
    server.serve_forever()
(venv) C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream>python app.py
C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\app.py:4: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
Traceback (most recent call last):
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\app.py", line 247, in <module>
    monkey.patch_all()
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 1219, in patch_all
    patch_thread(Event=Event, _warnings=_warnings)
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 187, in ignores
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 749, in patch_thread
    _patch_existing_locks(threading_mod)
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 630, in _patch_existing_locks  
    if isinstance(o, rlock_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\_utils\_proxy.py", line 39, in __class__        
    return self.__get_proxied__().__class__
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\_utils\_proxy.py", line 43, in __get_proxied__  
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\lib\_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.Edit, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.  

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742


(venv) C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream>python app.py
C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\app.py:4: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
Traceback (most recent call last):
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\app.py", line 247, in <module>
    monkey.patch_all()
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 1219, in patch_all
    patch_thread(Event=Event, _warnings=_warnings)
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 187, in ignores
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 749, in patch_thread
    _patch_existing_locks(threading_mod)
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\gevent\monkey.py", line 630, in _patch_existing_locks  
    if isinstance(o, rlock_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\_utils\_proxy.py", line 39, in __class__        
    return self.__get_proxied__().__class__
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\_utils\_proxy.py", line 43, in __get_proxied__  
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lukas\OneDrive\Desktop\Fuckaroundy\TwilioBidirectionalStream\venv\Lib\site-packages\openai\lib\_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.Edit, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.  

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

### OS

Windows 

### Python version

Python v3.11.3

### Library version

openai 1.3.0

**Comment by bnkc** [comment]
I am working on a solution
