### ISSUE TITLE
peer closed connection without sending complete message body occurred when use different session to send msg at same time

### ISSUE THREAD

**Issue by Mrfranken** [openai/openai-python#873]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

background:

1) I used llama2 as backend for inferenceing
2) use chanlit to start a frontend for user.
And I created two users, then I logined with user in different browser.
If one session was inferencing now, and I send msg in another session, it will raise error as above.

1) And if I changed "openai_api_base" to openai api endpoint, everything works.
2) if I changed "openai_api_base" to my local api endpoint(for example llama2 service endpoint), it will raise error.

From above 3 and 4 seems like my local endpoint is  borken right? But I've tried use concurrent to send multiple requests at a same time, everything works. (my endpoints based on llama.cpp)

So I suspect if there is some differences between openai official endpoint with local endpoint, especially when use openai library to send multiple completions request to local endpoint.

Many thx

### To Reproduce

1. start a local llama2 service which based on llama.cpp and llama-cpp-python
2. start a frontend service based on chainlit
3. open two webpage in different browsers
4. to start to chat on frontend at same time, the later one will interrupt former one.

```

2023-11-24 00:19:39 - Your app is available at http://localhost:8001
2023-11-24 00:19:47 - HTTP Request: POST http://localhost:8000/v1/chat/completions "HTTP/1.1 200 OK"
2023-11-24 00:19:49 - Error in LangchainTracer.on_llm_error callback: IndexError('list index out of range')
2023-11-24 00:19:49 - peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_transports/default.py", line 249, in __aiter__
    async for part in self._httpcore_stream:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_async/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "/Users/vince/Downloads/myworkspace/llm/llm/chainlit_test/profile/app.py", line 92, in on_message
    async for chunk in runnable.astream(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1802, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1788, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1158, in _atransform_stream_with_config
    async for chunk in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1761, in _atransform
    async for output in final_pipeline:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/output_parser.py", line 343, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1158, in _atransform_stream_with_config
    async for chunk in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/output_parser.py", line 321, in _atransform
    async for chunk in input:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/utils/aiter.py", line 97, in tee_peer
    item = await iterator.__anext__()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 683, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/base.py", line 273, in astream
    raise e
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/base.py", line 262, in astream
    async for chunk in self._astream(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 469, in _astream
    async for chunk in await acompletion_with_retry(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/_streaming.py", line 94, in __aiter__
    async for item in self._iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/_streaming.py", line 123, in __stream__
    async for sse in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/_streaming.py", line 98, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/_streaming.py", line 190, in aiter
    async for line in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_models.py", line 966, in aiter_lines
    async for text in self.aiter_text():
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_models.py", line 953, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_models.py", line 932, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_models.py", line 990, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_transports/default.py", line 248, in __aiter__
    with map_httpcore_exceptions():
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-11-24 00:19:49 - HTTP Request: POST http://localhost:8000/v1/chat/completions "HTTP/1.1 200 OK"
```

### Code snippets

```Python
import json
from typing import Optional

import chainlit as cl
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.schema import StrOutputParser
from langchain.schema.runnable import Runnable
from langchain.schema.runnable.config import RunnableConfig
import platform

url = 'xxxx'  # local service endpoint
url = 'openai endpoint'


@cl.set_chat_profiles
async def chat_profile(current_user: cl.AppUser):
    if "admin_user" not in current_user.tags:
        # Default to 3.5 when not admin
        return [
            cl.ChatProfile(
                name="GPT-3.5",
                markdown_description="The underlying LLM model is **GPT-3.5**.",
                icon="https://picsum.photos/200",
            )
        ]

    return [
        cl.ChatProfile(
            name="GPT-3.5",
            markdown_description="The underlying LLM model is **GPT-3.5**.",
            icon="https://picsum.photos/200",
        ),
        cl.ChatProfile(
            name="GPT-4",
            markdown_description="The underlying LLM model is **GPT-4**.",
            icon="https://picsum.photos/250",
        ),
    ]


@cl.password_auth_callback
def auth_callback(username: str, password: str) -> Optional[cl.AppUser]:
    auth = None
    with open('authentication.json', 'r') as f:
        auth = json.load(f)
    if (username, password) == ("admin", "admin"):
        return cl.AppUser(
            username="admin", role="ADMIN", provider="credentials", tags=["admin_user"]
        )
    elif username == auth.get(username, None):
        return cl.AppUser(
            username=username, role="USER", provider="credentials", tags=["regular_user"]
        )
    else:
        return None


@cl.on_chat_start
async def on_chat_start():
    app_user = cl.user_session.get("user")
    chat_profile = cl.user_session.get("chat_profile")
    await cl.Message(
        content=f"starting chat with {app_user.username} using the {chat_profile} chat profile"
    ).send()

    model = ChatOpenAI(temperature=0.0, openai_api_base=url, openai_api_key="xxx", max_tokens=2048, streaming=True)
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                # "You're a very knowledgeable historian who provides accurate and eloquent answers to historical questions.",
                "You're a Linux expert who provides accurate and eloquent answers to Linux system related questions. Only answer the question about Linux"
            ),
            ("human", "{question}"),
        ]
    )
    runnable = prompt | model | StrOutputParser()
    cl.user_session.set(app_user.username, runnable)


@cl.on_message
async def on_message(message: cl.Message):
    runnable = cl.user_session.get(message.author)  # type: Runnable
    print(message.author, message.content)
    msg = cl.Message(content="")

    async for chunk in runnable.astream(
            {"question": message.content},
            config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await msg.stream_token(chunk)
```

### OS

macos

### Python version

python 3.10

### Library version

openai 1.3.5

**Comment by Mrfranken** [comment]
issue solved,  root cause due to other libs.

**Comment by pq-dong** [comment]
> issue solved, root cause due to other libs.

Could you please explain it in detail? I’m facing the same issue and really need your help.
