### ISSUE TITLE
tab completion in ipython crashes interpreter

### ISSUE THREAD

**Issue by stephantul** [openai/openai-python#896]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When using tab completion on `openai` in interactive mode, my interpreter shows a big traceback and crashes ipython. 

```
Traceback (most recent call last):
  File "/path/lib/python3.10/site-packages/IPython/core/completer.py", line 3171, in _complete
    result = matcher(context)
  File "/path/lib/python3.10/site-packages/IPython/core/completer.py", line 2707, in custom_completer_matcher
    matches = self.dispatch_custom_completer(context.token) or []
  File "/path/lib/python3.10/site-packages/IPython/core/completer.py", line 2747, in dispatch_custom_completer
    res = c(event)
  File "/path/lib/python3.10/site-packages/IPython/core/completerlib.py", line 272, in module_completer
    return module_completion(event.line)
  File "/path/lib/python3.10/site-packages/IPython/core/completerlib.py", line 249, in module_completion
    completion_list = try_import('.'.join(mod[:-1]), True)
  File "/path/lib/python3.10/site-packages/IPython/core/completerlib.py", line 183, in try_import
    completions.extend( [attr for attr in dir(m) if
  File "/path/lib/python3.10/site-packages/IPython/core/completerlib.py", line 184, in <listcomp>
    is_importable(m, attr, only_modules)])
  File "/path/lib/python3.10/site-packages/IPython/core/completerlib.py", line 153, in is_importable
    return inspect.ismodule(getattr(module, attr))
  File "/.pyenv/versions/3.10.8/lib/python3.10/inspect.py", line 189, in ismodule
    return isinstance(object, types.ModuleType)
  File "/path/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 39, in __class__
    return self.__get_proxied__().__class__
  File "/path/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
    return self.__load__()
  File "/path/lib/python3.10/site-packages/openai/lib/_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Audio, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
``` 

### To Reproduce

Open an interactive ipython session.

type `from openai` and press your tab key.

### OS

macOS

### Python version

v3.10.8

### Library version

openai v1.3.6

**Comment by RobertCraigie** [comment]
Sorry about this, we'll have a fix out shortly.

**Comment by RobertCraigie** [comment]
A fix for this will be included in the next release!
